"""The vocabulary that defines what "AI-adjacent" means for discovery.

Deliberately broad. The brief was "anything that touches AI", so recall matters
more than precision here — the classifier downstream is what decides what
actually belongs, and it can only judge repos discovery has found.

Topics are GitHub topic slugs. They are queried directly, and any topic seen on
a confirmed AI repo is fed back in (see `discovery.snowball_topics`), so this
list is a seed rather than a fixed universe.
"""

from __future__ import annotations

# Seed topics, grouped only for readability — they are queried as a flat set.
SEED_TOPICS: tuple[str, ...] = (
    # general
    "ai",
    "artificial-intelligence",
    "machine-learning",
    "deep-learning",
    "neural-network",
    "ml",
    "mlops",
    "data-science",
    "aiops",
    # LLM core
    "llm",
    "llms",
    "large-language-models",
    "gpt",
    "chatgpt",
    "openai",
    "anthropic",
    "claude",
    "gemini",
    "llama",
    "mistral",
    "qwen",
    "deepseek",
    "transformer",
    "transformers",
    "language-model",
    "foundation-models",
    "generative-ai",
    "genai",
    "text-generation",
    "instruction-tuning",
    # agents & tooling
    "ai-agents",
    "agents",
    "agent",
    "autonomous-agents",
    "multi-agent",
    "agentic",
    "agentic-ai",
    "ai-agent-framework",
    "tool-use",
    "function-calling",
    "mcp",
    "model-context-protocol",
    "mcp-server",
    "ai-assistant",
    "copilot",
    "ai-coding",
    "code-generation",
    "coding-agent",
    # retrieval
    "rag",
    "retrieval-augmented-generation",
    "vector-database",
    "vector-search",
    "embeddings",
    "semantic-search",
    "knowledge-graph",
    "hybrid-search",
    # serving & infra
    "inference",
    "inference-engine",
    "llm-inference",
    "llm-serving",
    "vllm",
    "quantization",
    "gguf",
    "onnx",
    "tensorrt",
    "model-serving",
    "gpu",
    "cuda",
    "distributed-training",
    "llmops",
    "ai-infrastructure",
    "edge-ai",
    "on-device-ai",
    # training
    "fine-tuning",
    "lora",
    "peft",
    "rlhf",
    "reinforcement-learning",
    "transfer-learning",
    "pretraining",
    "model-training",
    "dpo",
    # modalities
    "computer-vision",
    "image-generation",
    "text-to-image",
    "diffusion",
    "diffusion-models",
    "stable-diffusion",
    "image-segmentation",
    "object-detection",
    "ocr",
    "multimodal",
    "vision-language-model",
    "speech-recognition",
    "text-to-speech",
    "speech-to-text",
    "tts",
    "asr",
    "voice-cloning",
    "audio-generation",
    "music-generation",
    "text-to-video",
    "video-generation",
    "3d-generation",
    # nlp classic
    "nlp",
    "natural-language-processing",
    "named-entity-recognition",
    "sentiment-analysis",
    "text-classification",
    "translation",
    "summarization",
    # prompt / eval / safety
    "prompt-engineering",
    "prompting",
    "prompt-injection",
    "llm-evaluation",
    "evaluation",
    "observability",
    "guardrails",
    "ai-safety",
    "alignment",
    "red-teaming",
    "hallucination",
    # data & frameworks
    "pytorch",
    "tensorflow",
    "jax",
    "keras",
    "scikit-learn",
    "huggingface",
    "langchain",
    "llamaindex",
    "dataset",
    "datasets",
    "synthetic-data",
    "feature-store",
    "data-labeling",
    "annotation-tool",
    # applied
    "chatbot",
    "conversational-ai",
    "recommendation-system",
    "time-series",
    "anomaly-detection",
    "forecasting",
    "robotics",
    "self-driving",
    "reinforcement-learning-environments",
    "bioinformatics-ai",
    "ai-art",
    "character-ai",
    "digital-human",
)

# Free-text queries for projects that never bothered with topics. Searched over
# name, description and README.
SEED_KEYWORDS: tuple[str, ...] = (
    "llm",
    "large language model",
    "ai agent",
    "agentic",
    "chatbot",
    "retrieval augmented generation",
    "vector database",
    "prompt engineering",
    "fine-tuning llm",
    "text to image",
    "speech recognition",
    "neural network",
    "machine learning framework",
    "inference server",
    "model context protocol",
    "openai api",
    "anthropic claude",
    "local llm",
    "open source llm",
    "ai coding assistant",
    "multimodal model",
    "diffusion model",
    "embedding model",
    "ai evaluation",
    "llm observability",
)

# Curated list repos are a very cheap, very high-signal recall boost: they are
# maintained by humans who already did the filtering.
AWESOME_LISTS: tuple[str, ...] = (
    "e2b-dev/awesome-ai-agents",
    "Hannibal046/Awesome-LLM",
    "punkpeye/awesome-mcp-servers",
    "mahseema/awesome-ai-tools",
    "steven2358/awesome-generative-ai",
    "josephmisiti/awesome-machine-learning",
    "ChristosChristofidis/awesome-deep-learning",
    "jtoy/awesome-tensorflow",
    "bharathgs/Awesome-pytorch-list",
    "keon/awesome-nlp",
    "jbhuang0604/awesome-computer-vision",
    "awesome-foundation-models/awesome-foundation-models",
    "kyrolabs/awesome-langchain",
    "DsaltYfish/awesome-rag",
    "wangrongsheng/awesome-LLM-resourses",
    "eugeneyan/open-llms",
    "underlines/awesome-ml",
    "modelcontextprotocol/servers",
)

# Package names whose dependents are almost certainly AI projects. Used against
# ecosyste.ms, which indexes dependency graphs we cannot get from GitHub search.
BELLWETHER_PACKAGES: dict[str, tuple[str, ...]] = {
    "pypi": (
        "torch",
        "transformers",
        "openai",
        "anthropic",
        "langchain",
        "llama-index",
        "vllm",
        "sentence-transformers",
        "diffusers",
        "accelerate",
        "peft",
        "datasets",
        "tiktoken",
        "chromadb",
        "litellm",
        "instructor",
        "guidance",
        "outlines",
        "mcp",
    ),
    "npm": (
        "openai",
        "@anthropic-ai/sdk",
        "langchain",
        "@langchain/core",
        "ai",
        "@huggingface/inference",
        "@modelcontextprotocol/sdk",
        "llamaindex",
        "onnxruntime-node",
        "@xenova/transformers",
    ),
}
